// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalweB62EMw-WMgwwYqdLCeHTN7IqKM6E',
    appId: '1:727616460135:web:05a73269cadb67f145cbc2',
    messagingSenderId: '727616460135',
    projectId: 'superscav-ce605',
    authDomain: 'superscav-ce605.firebaseapp.com',
    storageBucket: 'superscav-ce605.firebasestorage.app',
    measurementId: 'G-FJYLQ55GZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRzLGQcGxw0isWTj-_9-QXEzpcT3H4u9w',
    appId: '1:727616460135:android:1cc0d6ab14e9686745cbc2',
    messagingSenderId: '727616460135',
    projectId: 'superscav-ce605',
    storageBucket: 'superscav-ce605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgn21WuPiP3-jpMbNUgJfpM1_1sdvVyY',
    appId: '1:727616460135:ios:5f8cc79d96ef33a745cbc2',
    messagingSenderId: '727616460135',
    projectId: 'superscav-ce605',
    storageBucket: 'superscav-ce605.firebasestorage.app',
    iosBundleId: 'com.nograss.superscav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgn21WuPiP3-jpMbNUgJfpM1_1sdvVyY',
    appId: '1:727616460135:ios:61eac958100b6d5345cbc2',
    messagingSenderId: '727616460135',
    projectId: 'superscav-ce605',
    storageBucket: 'superscav-ce605.firebasestorage.app',
    iosBundleId: 'com.nograss.superscav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCalweB62EMw-WMgwwYqdLCeHTN7IqKM6E',
    appId: '1:727616460135:web:a5552f227faa3cb845cbc2',
    messagingSenderId: '727616460135',
    projectId: 'superscav-ce605',
    authDomain: 'superscav-ce605.firebaseapp.com',
    storageBucket: 'superscav-ce605.firebasestorage.app',
    measurementId: 'G-3TY1W2PHQ9',
  );

}